# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl

os:
  - linux
  - osx
osx_image: xcode9 

compiler: clang

env:
  global: 
    - RGL_USE_NULL=TRUE
    - DISPLAY=:99.0
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
r_check_args: --as-cran --install-args=--build

before_install:
  - ulimit -n 2048
  - export PROJ_DIR=`basename $PWD`    
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
  - x=`export_clang_cxx`; eval ${x}
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      no_open_mp ;
    fi
  - clang_cxx    
  - cat DESCRIPTION
  - start_xvfb ;
  - export rver=`r_version`; echo $rver ;
  - fftw_install ;

after_success:
  - dump_logs

after_failure:
  - dump_logs
